### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.auxiliary_loss_trainer' 

### ISSUE THREAD

**Issue by taktak1** [ashispati/InpaintNet#1]
> Traceback (most recent call last):
> 　File "train_arnn_baseline.py", line 7, in <module>
> 　　from AnticipationRNN.anticipation_rnn_gauss_reg_model import *
> 　File "InpaintNet/AnticipationRNN/__init__.py", line 1, in <module>
> 　　from . import anticipation_rnn_gauss_reg_model, anticipation_rnn_trainer, anticipation_rnn_tester
> 　File "InpaintNet/AnticipationRNN/anticipation_rnn_trainer.py", line 3, in <module>
> 　　from utils.auxiliary_loss_trainer import AuxiliaryLossTrainer
> ModuleNotFoundError: No module named 'utils.auxiliary_loss_trainer'

The auxiliary_loss_trainer and AuxiliaryLossTrainer do not seem to exist. 
What should I write in the code here?

@ashispati

**Comment by ashispati** [comment]
Ah...that is some stuff that I was experimenting with but no longer use. Thanks for spotting it. Fixing this in the next commit.
