### ISSUE TITLE
No such file or directory: "InpaintNet/AnticipationRNN/models/AnticipationRNNReg(FolkDatasetNBars(16['beatmarker', 'tick'])25000_train,10,2,256,256,256,2,0.2,0.2,True,),tf" 

### ISSUE THREAD

**Issue by taktak1** [ashispati/InpaintNet#2]
> 　File "train_arnn_reg.py", line 113, in main
> 　　log=log
> 　File "InpaintNet/utils/trainer.py", line 115, in train_model
> 　　self.model.save()
> 　File "InpaintNet/utils/model.py", line 21, in save
> 　　torch.save(self.state_dict(), self.filepath)
> 　File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 260, in save
> 　　return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
> 　File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 183, in _with_file_like
> 　　f = open(f, mode)
> FileNotFoundError: [Errno 2] No such file or directory: "InpaintNet/AnticipationRNN/models/AnticipationRNNReg(FolkDatasetNBars(16['beatmarker', 'tick'])25000_train,10,2,256,256,256,2,0.2,0.2,True,),tf"

These files probably do not exist.
How do I get these files?

The same problem occurs in train_arnn_baseline.py.
>"AnticipationRNNBaseline(FolkDatasetNBars(16['beatmarker','tick'])25000_train,10,2,256,256,256,2,0.2,0.2,True,),tf"

@ashispati

**Comment by ashispati** [comment]
The code expects a folder to save checkpoints. It should work fine if you create a folder named `models` inside the `AnticipationRNN` folder. I have added a fix in the latest commit which would create these folders automatically.

**Comment by taktak1** [comment]
Thank you for your support many times.
